# Generated by Django 6.0.3 on 2026-04-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_code', models.CharField(max_length=50, unique=True)),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('father_phone', models.CharField(max_length=15)),
                ('mother_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
