# Generated by Django 6.0.3 on 2026-04-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_student_bus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
    ]
