# Generated by Django 6.0.3 on 2026-04-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_bus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trip_type', models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], max_length=10)),
                ('school_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('distance_km', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.bus')),
            ],
        ),
    ]
