# Generated by Django 6.0.3 on 2026-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='school_name',
            new_name='source_name',
        ),
        migrations.AddField(
            model_name='trip',
            name='source_type',
            field=models.CharField(choices=[('school', 'School'), ('company', 'Company')], default='school', max_length=20),
        ),
    ]
