# Generated by Django 6.0.3 on 2026-04-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_rename_school_name_trip_source_name_trip_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.bus'),
        ),
    ]
