# Generated by Django 6.0.3 on 2026-04-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_alter_trip_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.trip'),
        ),
    ]
