# Generated by Django 6.0.3 on 2026-04-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_student_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bus',
        ),
    ]
