# Generated by Django 6.0.3 on 2026-04-06 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_maintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liters', models.FloatField()),
                ('cost', models.FloatField()),
                ('odometer_reading', models.FloatField(help_text='Total KM reading at time of fuel fill')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='transport.bus')),
            ],
        ),
    ]
