# Generated by Django 6.0.3 on 2026-04-08 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_payer_charge_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50)),
                ('is_part_time', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.bus')),
            ],
        ),
    ]
