# Generated by Django 6.0.3 on 2026-04-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_salaryadvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='monthly_salary',
            field=models.FloatField(default=0),
        ),
    ]
