# Generated by Django 6.0.3 on 2026-04-11 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_driver_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellog',
            name='odometer_reading',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='BusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('rc', 'Registration Certificate'), ('permit', 'Contract Carriage Permit'), ('fitness', 'Fitness Certificate'), ('insurance', 'Insurance'), ('puc', 'PUC Certificate'), ('other', 'Other')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='bus_documents/')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transport.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField()),
                ('total_amount', models.FloatField()),
                ('monthly_repayment', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='transport.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='transport.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transport.bus')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sequence', models.IntegerField()),
                ('estimated_time', models.CharField(blank=True, max_length=20, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.route')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
