# Generated by Django 6.0.3 on 2026-04-14 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_externalcontact_driver_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('applies_to', models.CharField(blank=True, help_text='Leave blank for all, or enter school/company name', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='days_of_week',
            field=models.JSONField(default=list, help_text="List of days this trip runs e.g. ['mon','tue','wed','thu','fri']"),
        ),
        migrations.AddField(
            model_name='triplog',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triplog',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('merged', 'Merged with another bus'), ('driver_changed', 'Driver changed'), ('holiday', 'Holiday'), ('other', 'Other issue')], default='normal', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='triplog',
            unique_together={('trip', 'date')},
        ),
    ]
